gina = Artist.create(email: "gina@gmail.com", password: "123", password_confirmation: "123", name: "Gina", img_url: "/images/artist_gina.jpg")
joshua = Artist.create(email: "joshua@gmail.com", password: "123", password_confirmation: "123", name: "Joshua", img_url: "google.com")
emi = Artist.create(email: "emi@gmail.com", password: "123", password_confirmation: "123", name: "Emi", img_url: "google.com")

juan = Bidder.create(email: "juan@gmail.com", password: "123", password_confirmation: "123", name: "Juan")
kevin = Bidder.create(email: "kevin@gmail.com", password: "123", password_confirmation: "123", name: "Kevin")

boi = Art.create(artist_id: joshua.id, title: "Boi", starting_price: 15, img_url: '/images/joshua_filemon_3.jpg')
figures = Art.create(artist_id: gina.id, title: "Figures", starting_price: 15, img_url: '/images/figures.jpg')
orange = Art.create(artist_id: emi.id, title: "Orange Is The New Black", starting_price: 15, img_url: '/images/emi_anderson_1.jpg')
green = Art.create(artist_id: emi.id, title: "Green Girl", starting_price: 15, img_url: '/images/emi_anderson_2.jpg')
joshua5 = Art.create(artist_id: joshua.id, title: "1984", starting_price: 15, img_url: '/images/joshua_filemon_5.jpg')
break_ya_neck = Art.create(artist_id: gina.id, title: "Break Ya Neck", starting_price: 15, img_url: '/images/break_ya_neck.jpg')
westworld = Art.create(artist_id: joshua.id, title: "Westworld", starting_price: 15, img_url: '/images/joshua_filemon_7.jpg')
cow_skull = Art.create(artist_id: gina.id, title: "Cow Skull", starting_price: 20, img_url: '/images/cow_skull.jpg')
astoria_blvd = Art.create(artist_id: gina.id, title: "Astoria Blvd", starting_price: 12, img_url: '/images/astoria_blvd.jpg')
fremont = Art.create(artist_id: gina.id, title: "Fremont", starting_price: 30, img_url: '/images/fremont.jpg')
shipyard = Art.create(artist_id: gina.id, title: "Shipyard", starting_price: 15, img_url: '/images/shipyard.jpg')
emi5 = Art.create(artist_id: emi.id, title: "Emi 5", starting_price: 15, img_url: '/images/emi_anderson_5.jpg')
tiffany = Art.create(artist_id: gina.id, title: "Tiffany", starting_price: 15, img_url: '/images/tiffany.jpg')
emi3 = Art.create(artist_id: emi.id, title: "Emi 3", starting_price: 15, img_url: '/images/emi_anderson_3.jpg')
joshua1 = Art.create(artist_id: joshua.id, title: "Joshua 1", starting_price: 15, img_url: '/images/joshua_filemon_1.jpg')
joshua2 = Art.create(artist_id: joshua.id, title: "Joshua 2", starting_price: 15, img_url: '/images/joshua_filemon_2.jpg')
joshua4 = Art.create(artist_id: joshua.id, title: "Joshua 4", starting_price: 15, img_url: '/images/joshua_filemon_4.jpg')
joshua6 = Art.create(artist_id: joshua.id, title: "Joshua 6", starting_price: 15, img_url: '/images/joshua_filemon_6.jpg')
joshua8 = Art.create(artist_id: joshua.id, title: "Joshua 8", starting_price: 15, img_url: '/images/joshua_filemon_8.jpg')

Bidding.create(art_id: tiffany.id, bidder_id: juan.id, bid_amount: 30)
Bidding.create(art_id: fremont.id, bidder_id: juan.id, bid_amount: 40)

photography = Tag.create(name: "photography")
color = Tag.create(name: "color")
line_drawing = Tag.create(name: "line_drawing")
painting = Tag.create(name: "painting")

ArtTag.create(art_id: boi.id, tag_id: line_drawing.id)
ArtTag.create(art_id: figures.id, tag_id: line_drawing.id)
ArtTag.create(art_id: orange.id, tag_id: color.id)
ArtTag.create(art_id: green.id, tag_id: color.id)
ArtTag.create(art_id: joshua5.id, tag_id: color.id)
ArtTag.create(art_id: break_ya_neck.id, tag_id: color.id)
ArtTag.create(art_id: westworld.id, tag_id: color.id)
ArtTag.create(art_id: cow_skull.id, tag_id: color.id)
ArtTag.create(art_id: cow_skull.id, tag_id: line_drawing.id)
ArtTag.create(art_id: astoria_blvd.id, tag_id: photography.id)
ArtTag.create(art_id: fremont.id, tag_id: photography.id)
ArtTag.create(art_id: shipyard.id, tag_id: color.id)
ArtTag.create(art_id: shipyard.id, tag_id: photography.id)
ArtTag.create(art_id: emi5.id, tag_id: color.id)
ArtTag.create(art_id: emi5.id, tag_id: painting.id)
ArtTag.create(art_id: tiffany.id, tag_id: line_drawing.id)
ArtTag.create(art_id: emi3.id, tag_id: color.id)
ArtTag.create(art_id: emi3.id, tag_id: painting.id)
ArtTag.create(art_id: joshua1.id, tag_id: line_drawing.id)
ArtTag.create(art_id: joshua2.id, tag_id: painting.id)
ArtTag.create(art_id: joshua4.id, tag_id: color.id)
ArtTag.create(art_id: joshua6.id, tag_id: line_drawing.id)
ArtTag.create(art_id: joshua8.id, tag_id: painting.id)
